export default {
    primary: '#fc5c65',
    secondary: '#4ecdc4',
    themeColor: "royalblue",
    white: '#fff',
    black: '#000',
    medium: '#6e6969',
    light: '#eceaea',
    lightgray: 'lightGray',
    dark: '#0c0c0c',
    grey: 'grey',
    danger: '#ff5252',
    linkColor: '#0054a8',
    buttonColor: '#0071E3',
    backgroundColor: '#F5F5F5',
    touchableButtonColor: '#0379CE',
}
